spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    spring:
      jpa:
        properties:
          hibernate:
            jdbc:
              time_zone: UTC
  jackson:
    time-zone: UTC